#!/bin/bash
sudo passwd -l root
echo Root account locked.
read -n 1

sudo updatedb
echo Database updated.
read -n 1

sudo apt-get -y update
echo Available updates updated. 
read -n 1

sudo ufw enable
echo Firewall enabled.
read -n 1

sudo sysctl -n net.ipv4.tcp_syncookies
echo Cookies secured.
read -n 1

for $i in $(cat users)
  do
  sudo deluser $i sudo
  yes PASSword1234!!! | sudo passwd $1
done
echo All users demoted.
echo All passwords changed.
