#!/bin/bash
locate *.mp3
echo MP3 files located.
read -p "Would you like to delete the music files? [y/n]: " delConf

if [ $delConf == 'n' ]; then
   echo "Ending script..."
else
   echo "Deleting music files...";
   
   for i in $(locate *.mp3)
 		do
	    sudo rm $i
   done
   
   echo MP3 files deleted.
fi


