#!/bin/bash
service --status-all;
loop=true;

while $loop; 
    do
    read -p "What services would you like to stop? [y/n]: " service
    if [ $service == 'n' ]; then
        echo "Ending script..."
        loop=false;
    else
        echo "Stopping...";
        sudo stop $service;
    fi
done
