#!/bin/bash

##############################################

    sudo passwd -l root
    echo Root account locked.

##############################################

    sudo updatedb
    echo Database updated.

##############################################

sudo ufw enable

##############################################

for i in $(cat hackingprograms)
    do
    sudo apt-get purge --auto - remove -y -q $i
done

##############################################

    sudo echo "allow-guest = false" >> /etc/lightdm/lightdm.conf
    sudo restart lightdm
